INSERT INTO learning_notes (id, member_id, original_content, corrected_content) VALUES
-- ===== GRAMMAR 34개 =====
(1, 1, 'He dont know the answer', 'He does not know the answer'),
(2, 1, 'She walk to school every day', 'She walks to school every day'),
(3, 1, 'They is eating dinner now', 'They are eating dinner now'),
(4, 1, 'I am boring in this class', 'I am bored in this class'),
(5, 1, 'We was tired after trip', 'We were tired after the trip'),
(6, 1, 'He go to market yesterday', 'He went to the market yesterday'),
(7, 1, 'She do homework now', 'She is doing homework now'),
(8, 1, 'My brother like soccer', 'My brother likes soccer'),
(9, 1, 'You was right about that', 'You were right about that'),
(10, 1, 'They doesnt understand me', 'They do not understand me'),
(11, 1, 'He have many friends', 'He has many friends'),
(12, 1, 'The cat sleep on the table', 'The cat sleeps on the table'),
(13, 1, 'She were my best friend', 'She was my best friend'),
(14, 1, 'It do not matter now', 'It does not matter now'),
(15, 1, 'He am trying to fix it', 'He is trying to fix it'),
(16, 1, 'The students was loud', 'The students were loud'),
(17, 1, 'My sister play piano well', 'My sister plays the piano well'),
(18, 1, 'The dog chase the ball yesterday', 'The dog chased the ball yesterday'),
(19, 1, 'He not come to school today', 'He did not come to school today'),
(20, 1, 'We goes to same class', 'We go to the same class'),
(21, 1, 'She not like cold weather', 'She does not like cold weather'),
(22, 1, 'He were eating lunch', 'He was eating lunch'),
(23, 1, 'The kids plays outside', 'The kids play outside'),
(24, 1, 'I is hungry', 'I am hungry'),
(25, 1, 'She dont likes apples', 'She does not like apples'),
(26, 1, 'He runned fast', 'He ran fast'),
(27, 1, 'We is ready to go', 'We are ready to go'),
(28, 1, 'They was happy', 'They were happy'),
(29, 1, 'My mom cook dinner yesterday', 'My mom cooked dinner yesterday'),
(30, 1, 'He didnt knew the truth', 'He did not know the truth'),
(31, 1, 'She tell me the story yesterday', 'She told me the story yesterday'),
(32, 1, 'We was planning a party', 'We were planning a party'),
(33, 1, 'He is more taller than me', 'He is taller than me'),
(34, 1, 'This book are interesting', 'This book is interesting'),

-- ===== VOCABULARY 33개 =====
(35, 1, 'I drink water fast', 'I drink water quickly'),
(36, 1, 'He speak English good', 'He speaks English well'),
(37, 1, 'She buyed a new phone', 'She bought a new phone'),
(38, 1, 'He have two dog', 'He has two dogs'),
(39, 1, 'I am confuse about homework', 'I am confused about the homework'),
(40, 1, 'This coffee is very hotly', 'This coffee is very hot'),
(41, 1, 'He is a kindly person', 'He is a kind person'),
(42, 1, 'She runs quick', 'She runs quickly'),
(43, 1, 'This soup taste bad', 'This soup tastes bad'),
(44, 1, 'I need a new informations', 'I need new information'),
(45, 1, 'He is more smart than me', 'He is smarter than me'),
(46, 1, 'She ate healthy food very frequent', 'She ate healthy food very frequently'),
(47, 1, 'He is a good cooker', 'He is a good cook'),
(48, 1, 'The movie was bored', 'The movie was boring'),
(49, 1, 'She is talent in music', 'She is talented in music'),
(50, 1, 'My phone battery die fastly', 'My phone battery dies quickly'),
(51, 1, 'We walked slow on the beach', 'We walked slowly on the beach'),
(52, 1, 'He is a success person', 'He is a successful person'),
(53, 1, 'The class was very interest', 'The class was very interesting'),
(54, 1, 'She study hardly every day', 'She studies hard every day'),
(55, 1, 'He drive very dangerous', 'He drives very dangerously'),
(56, 1, 'This bag is more heavy', 'This bag is heavier'),
(57, 1, 'She is a beauty girl', 'She is a beautiful girl'),
(58, 1, 'He explained it very clear', 'He explained it very clearly'),
(59, 1, 'This test was difficulty', 'This test was difficult'),
(60, 1, 'I am very exciting today', 'I am very excited today'),
(61, 1, 'The shoes is comfortablely', 'The shoes are comfortable'),
(62, 1, 'He talked very silent', 'He talked very quietly'),
(63, 1, 'This solution is effective but slowlier', 'This solution is effective but slower'),
(64, 1, 'She learn English very quick', 'She learns English very quickly'),
(65, 1, 'He is a high skill worker', 'He is a highly skilled worker'),
(66, 1, 'The weather is more colder', 'The weather is colder'),
(67, 1, 'My cat sleep soft on sofa', 'My cat sleeps softly on the sofa'),

-- ===== TRANSLATION 33개 (한국어 포함) =====
(68, 1, '나는 오늘 school 가기 싫어', 'I do not want to go to school today'),
(69, 1, '이 음식 really 맛있다', 'This food is really delicious'),
(70, 1, '저 사람은 my friend 가 아니야', 'That person is not my friend'),
(71, 1, '내일 비가 올 것 같아 I think', 'I think it will rain tomorrow'),
(72, 1, '나는 한국에서 job 을 찾고 있다', 'I am looking for a job in Korea'),
(73, 1, '나는 어제 friend 하고 놀았다', 'I hung out with a friend yesterday'),
(74, 1, '지하철 station 까지 걸어갔어', 'I walked to the subway station'),
(75, 1, '오늘 날씨 너무 good 하다', 'The weather is very good today'),
(76, 1, '나는 영어 study 가 필요해', 'I need to study English'),
(77, 1, '여기 음식 너무 spicy 야', 'The food here is too spicy'),
(78, 1, '나는 지금 회사에 go 중이다', 'I am on my way to the company'),
(79, 1, '그 사람은 정말 kind 해', 'That person is really kind'),
(80, 1, '나는 내일 movie 볼 예정이야', 'I am going to watch a movie tomorrow'),
(81, 1, '우리 집은 subway 근처야', 'My house is near the subway'),
(82, 1, '저 곳은 너무 far 해', 'That place is too far'),
(83, 1, '나는 피곤해서 rest 하고 싶어', 'I want to rest because I am tired'),
(84, 1, '오늘 meeting 진짜 길었다', 'Today’s meeting was really long'),
(85, 1, '나는 지금 커피 shop 에 있다', 'I am at a coffee shop right now'),
(86, 1, '숙제 너무 difficult 해서 싫어', 'I hate the homework because it is too difficult'),
(87, 1, '나는 bus 타고 왔어', 'I came by bus'),
(88, 1, '지금 너무 sleepy 하다', 'I am so sleepy right now'),
(89, 1, '이 게임 너무 fun 해', 'This game is so fun'),
(90, 1, '나는 저녁에 family 만나', 'I will meet my family in the evening'),
(91, 1, '여기 분위기 정말 nice 하다', 'The atmosphere here is really nice'),
(92, 1, '오늘은 정말 lucky 한 날이야', 'Today is a really lucky day'),
(93, 1, '나는 주말에 운동할거야', 'I will exercise on the weekend'),
(94, 1, '그게 정말 problem 이야', 'That is really a problem'),
(95, 1, '나는 지금 music 듣는 중', 'I am listening to music right now'),
(96, 1, '오늘 너무 busy 했다', 'I was very busy today'),
(97, 1, '나는 새로운 skills 배우는 중', 'I am learning new skills'),
(98, 1, '여기 너무 noise 나', 'It is too noisy here'),
(99, 1, '지금 나 너무 hungry 하다', 'I am so hungry right now'),
(100, 1, '나는 오늘 기분이 good 하다', 'I feel good today');