INSERT INTO reports (reported_msg_content, target_member_id, status, category, reported_reason)
VALUES ('User used rude language in chat', 1, 'WAITING', 'ABUSE', 'Offensive message detected'),
       ('User sent suspicious link', 2, 'WAITING', 'SCAM', 'Possible phishing attempt'),
       ('User posted inappropriate content', 3, 'REVIEWING', 'INAPPROPRIATE', 'Content violates guidelines'),
       ('Spam repeated messages in chat', 4, 'WAITING', 'OTHER', 'Repeated spam behavior'),
       ('User insulted another member', 5, 'APPROVED', 'ABUSE', 'Direct personal attack'),
       ('User attempted scam transaction', 6, 'REJECTED', 'SCAM', 'Not enough evidence'),
       ('User posted aggressive comments', 7, 'WAITING', 'ABUSE', 'Hostile tone'),
       ('Inappropriate nickname detected', 8, 'REVIEWING', 'INAPPROPRIATE', 'Nickname violates rules'),
       ('Suspicious activity in chat logs', 9, 'WAITING', 'SCAM', 'Unusual pattern recorded'),
       ('User shared private info publicly', 10, 'APPROVED', 'OTHER', 'Privacy violation'),
       ('User used discriminatory language', 11, 'WAITING', 'ABUSE', 'Hate speech related'),
       ('User repeatedly sent scam messages', 12, 'REVIEWING', 'SCAM', 'Repeated scam attempts'),
       ('User uploaded inappropriate images', 13, 'APPROVED', 'INAPPROPRIATE', 'Image violates content rules'),
       ('User misled others intentionally', 14, 'WAITING', 'OTHER', 'Misinformation spread'),
       ('User used insulting tone repeatedly', 15, 'REJECTED', 'ABUSE', 'Tone unclear'),
       ('User sent harmful link', 16, 'WAITING', 'SCAM', 'Link flagged as malicious'),
       ('User posted sexual content', 17, 'APPROVED', 'INAPPROPRIATE', 'Adult content detected'),
       ('User falsely reported others', 18, 'WAITING', 'OTHER', 'Suspicious reporting behavior'),
       ('User harassed other user', 19, 'REVIEWING', 'ABUSE', 'Bullying and harassment'),
       ('User tried impersonating admin', 20, 'APPROVED', 'SCAM', 'Impersonation confirmed'),
       ('User sent violent messages', 21, 'WAITING', 'ABUSE', 'Threatening tone'),
       ('User used banned words', 22, 'WAITING', 'INAPPROPRIATE', 'Filtered word detected'),
       ('User requested money illegally', 23, 'REVIEWING', 'SCAM', 'Unlawful request detected'),
       ('User spammed emojis', 24, 'REJECTED', 'OTHER', 'Not harmful enough'),
       ('User sent disturbing content', 25, 'WAITING', 'INAPPROPRIATE', 'Graphic content'),
       ('User insulted group chat members', 26, 'APPROVED', 'ABUSE', 'Multiple user complaints'),
       ('User asked for password', 27, 'WAITING', 'SCAM', 'Credential theft attempt'),
       ('User tried selling illegal items', 28, 'REVIEWING', 'OTHER', 'Illegal transaction attempt'),
       ('User used extreme profanity', 29, 'WAITING', 'ABUSE', 'Strong curse words detected'),
       ('User posted trolling messages', 30, 'WAITING', 'OTHER', 'Intentionally disruptive'),
       ('User shared malware file', 31, 'APPROVED', 'SCAM', 'File scanned as dangerous'),
       ('User mocked others repeatedly', 32, 'WAITING', 'ABUSE', 'Harassment pattern seen'),
       ('User posted discriminatory jokes', 33, 'REVIEWING', 'INAPPROPRIATE', 'Sensitive topic issue'),
       ('User tried tricking new users', 34, 'WAITING', 'SCAM', 'Deceptive behavior'),
       ('User sent threatening messages', 35, 'APPROVED', 'ABUSE', 'Threat confirmed'),
       ('User advertised external servers', 36, 'REJECTED', 'OTHER', 'Allowed under current rules'),
       ('User shared violent image', 37, 'WAITING', 'INAPPROPRIATE', 'Graphic material'),
       ('User repeatedly begged for money', 38, 'WAITING', 'SCAM', 'Fraud suspicion'),
       ('User used hate speech', 39, 'REVIEWING', 'ABUSE', 'Multiple flagged words'),
       ('User shared illegal streaming link', 40, 'WAITING', 'OTHER', 'Copyright violation'),
       ('User promoted scam investment', 41, 'APPROVED', 'SCAM', 'Confirmed scam'),
       ('User insulted staff member', 42, 'WAITING', 'ABUSE', 'Admin harassment'),
       ('User posted suggestive messages', 43, 'REVIEWING', 'INAPPROPRIATE', 'Borderline content'),
       ('User sent mass unsolicited messages', 44, 'WAITING', 'OTHER', 'Spam waves detected'),
       ('User impersonated another user', 45, 'APPROVED', 'SCAM', 'Identity abuse confirmed'),
       ('User used continuous profanity', 46, 'WAITING', 'ABUSE', 'Toxic language'),
       ('User posted explicit material', 47, 'APPROVED', 'INAPPROPRIATE', 'Explicit content'),
       ('User manipulated chat logs', 48, 'WAITING', 'OTHER', 'Suspicious manipulation'),
       ('User sent harmful prank links', 49, 'REVIEWING', 'SCAM', 'Malicious prank detected'),
       ('User spread false accusations', 50, 'WAITING', 'OTHER', 'Could cause conflict'),
       ('User made racist comments', 51, 'APPROVED', 'ABUSE', 'Severe violation'),
       ('User shared stolen content', 52, 'WAITING', 'OTHER', 'Copyright issues'),
       ('User attempted romance scam', 53, 'REVIEWING', 'SCAM', 'Behavior pattern detected'),
       ('User posted gore content', 54, 'APPROVED', 'INAPPROPRIATE', 'Severely graphic'),
       ('User insulted new members', 55, 'WAITING', 'ABUSE', 'Unfriendly behavior'),
       ('User tried selling fake items', 56, 'WAITING', 'SCAM', 'Fraud attempt'),
       ('User repeatedly used banned phrases', 57, 'REVIEWING', 'INAPPROPRIATE', 'Multiple triggers'),
       ('User shared dangerous challenges', 58, 'WAITING', 'OTHER', 'Safety hazard'),
       ('User sent abusive private messages', 59, 'APPROVED', 'ABUSE', 'Private harassment'),
       ('User attempted account theft', 60, 'REVIEWING', 'SCAM', 'Credential request'),
       ('User mocked victims of incidents', 61, 'WAITING', 'INAPPROPRIATE', 'Insensitive topic'),
       ('User posted disturbing jokes', 62, 'WAITING', 'OTHER', 'Borderline content'),
       ('User engaged in heated fights', 63, 'REVIEWING', 'ABUSE', 'Escalating conflict'),
       ('User spammed reaction buttons', 64, 'REJECTED', 'OTHER', 'Not serious'),
       ('User shared dangerous advice', 65, 'WAITING', 'OTHER', 'Potential harm'),
       ('User harassed minors', 66, 'APPROVED', 'ABUSE', 'Severe misconduct'),
       ('User sent fake giveaway message', 67, 'REVIEWING', 'SCAM', 'Misleading message'),
       ('User discussed restricted topics', 68, 'WAITING', 'INAPPROPRIATE', 'Not allowed topics'),
       ('User posted borderline NSFW text', 69, 'WAITING', 'INAPPROPRIATE', 'Ambiguous content'),
       ('User attempted pyramid scheme', 70, 'APPROVED', 'SCAM', 'Fraud structure detected'),
       ('User bullied repeatedly', 71, 'WAITING', 'ABUSE', 'Pattern of harassment'),
       ('User tricked others intentionally', 72, 'WAITING', 'SCAM', 'Manipulation attempt'),
       ('User shared disturbing memes', 73, 'REVIEWING', 'INAPPROPRIATE', 'Violent imagery'),
       ('User continued spam after warning', 74, 'WAITING', 'OTHER', 'Ignored warnings'),
       ('User disrespected moderators', 75, 'APPROVED', 'ABUSE', 'Disrespect confirmed'),
       ('User sent suspicious QR codes', 76, 'WAITING', 'SCAM', 'Possible malware'),
       ('User uploaded borderline graphic videos', 77, 'REVIEWING', 'INAPPROPRIATE', 'Graphic content'),
       ('User created multiple fake accounts', 78, 'WAITING', 'OTHER', 'Sockpuppet behavior'),
       ('User sent harmful rumor', 79, 'WAITING', 'OTHER', 'Potential misinformation'),
       ('User sent sexually suggestive emojis', 80, 'REVIEWING', 'INAPPROPRIATE', 'Uncomfortable behavior');
